# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a35tcpg236-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/laurensvandam/pairhmm_posit_hdl/posit_add/posit_add.cache/wt [current_project]
set_property parent.project_path /home/laurensvandam/pairhmm_posit_hdl/posit_add/posit_add.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/laurensvandam/pairhmm_posit_hdl/posit_add/posit_add.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /home/laurensvandam/pairhmm_posit_hdl/posit_add/posit_add.srcs/sources_1/imports/Posit-Adder/DSR_left_N_S.v
  /home/laurensvandam/pairhmm_posit_hdl/posit_add/posit_add.srcs/sources_1/imports/Posit-Adder/DSR_right_N_S.v
  /home/laurensvandam/pairhmm_posit_hdl/posit_add/posit_add.srcs/sources_1/imports/Posit-Adder/LOD_N.v
  /home/laurensvandam/pairhmm_posit_hdl/posit_add/posit_add.srcs/sources_1/imports/Posit-Adder/LZD_N.v
  /home/laurensvandam/pairhmm_posit_hdl/posit_add/posit_add.srcs/sources_1/imports/Posit-Adder/add_N.v
  /home/laurensvandam/pairhmm_posit_hdl/posit_add/posit_add.srcs/sources_1/imports/Posit-Adder/add_mantovf.v
  /home/laurensvandam/pairhmm_posit_hdl/posit_add/posit_add.srcs/sources_1/imports/Posit-Adder/data_extract.v
  /home/laurensvandam/pairhmm_posit_hdl/posit_add/posit_add.srcs/sources_1/imports/Posit-Adder/sub_N.v
  /home/laurensvandam/pairhmm_posit_hdl/posit_add/posit_add.srcs/sources_1/imports/Posit-Adder/posit_adder.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top posit_adder -part xc7a35tcpg236-3


write_checkpoint -force -noxdef posit_adder.dcp

catch { report_utilization -file posit_adder_utilization_synth.rpt -pb posit_adder_utilization_synth.pb }
